# These are supported funding model platforms

github: [moustachauve]
custom: ["https://www.paypal.com/donate/?hosted_button_id=RNBBDKLDM325Q", https://www.cgagnier.ca/, https://cookie-editor.cgagnier.ca/]
